### ISSUE TITLE
Alternative to displaying "N/A" when prediction is in past or when values are missing

### ISSUE THREAD

**Issue by michelleclearmetal** [clearmetal/design#25]
Related to issue: "Update container board columns with all predictions" https://app.zenhub.com/workspace/o/clearmetal/design/issues/15

## 1. 
If the prediction happened in the past. 
- Still show the last prediction in the column. Use a visual indicator to indicate that there is something different about this value than the other predictions (ex. grayed out value)
- Add columns for the actual times (Taken care of by https://app.zenhub.com/workspace/o/clearmetal/design/issues/465)

## 2. 
We did not make the prediction because it was not part of the transport plan (ex. a rail ramp availability)
- Solution: Write out: " - "

**Comment by marcoclearmetal** [comment]
@michelleclearmetal closing it as it is really old
